# Generated by Django 5.2.10 on 2026-01-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("difficulty", models.CharField(max_length=50)),
                ("duration_days", models.PositiveIntegerField()),
                ("price_usd", models.PositiveIntegerField()),
                ("location", models.CharField(default="Kyzyl Suu", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
