# Generated by Django 5.2.10 on 2026-01-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
