# Generated by Django 5.2.10 on 2026-01-23 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0002_tour_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tour",
            name="slug",
        ),
    ]
